# Generated by Django 3.0.4 on 2020-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200422_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField(default=0)),
                ('contact_email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('contact_post', models.CharField(max_length=50)),
                ('Contact_about', models.TextField()),
                ('contact_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
